/* KEYDEFS.H */

/* Extended key flag */
#define XF 0x100

/* Function keys */
#define K_F1	315
#define K_F2	316
#define K_F3	317
#define K_F4	318
#define K_F5	319
#define K_F6	320
#define K_F7	321
#define K_F8	322
#define K_F9	323
#define K_F10	324

/* Shifted function keys */
#define K_SF1	340
#define K_SF2	341
#define K_SF3	342
#define K_SF4	343
#define K_SF5	344
#define K_SF6	345
#define K_SF7	346
#define K_SF8	347
#define K_SF9	348
#define K_SF10	349

/* Control function keys */
#define K_CF1	350
#define K_CF2	351
#define K_CF3	352
#define K_CF4	353
#define K_CF5	354
#define K_CF6	355
#define K_CF7	356
#define K_CF8	357
#define K_CF9	358
#define K_CF10	359

/* ALT function keys */
#define K_AF1	360
#define K_AF2	361
#define K_AF3	362
#define K_AF4	363
#define K_AF5	364
#define K_AF6	365
#define K_AF7	366
#define K_AF8	367
#define K_AF9	368
#define K_AF10	369

/* Cursor keypad (NumLock off; not shifted) */
#define K_HOME	327
#define K_UP	328
#define K_PGUP	329
#define K_MIN  330
#define K_LEFT	331
#define K_CENT 332
#define K_RIGHT 333
#define K_PLUS	334
#define K_END	335
#define K_DOWN	336
#define K_PGDN	337

/* Control cursor keypad */
#define K_CHOME 375
#define K_CEND	 373
#define K_CPGUP 388
#define K_CPGDN 374
#define K_CLEFT 371
#define K_CRGHT 372

/* ALT keys */
#define K_ALTA	286
#define K_ALTB	304
#define K_ALTC	302
#define K_ALTD	288
#define K_ALTE	274
#define K_ALTF	289
#define K_ALTG	290
#define K_ALTH	291
#define K_ALTI	279
#define K_ALTJ	292
#define K_ALTK	293
#define K_ALTL	294
#define K_ALTM	306
#define K_ALTN	305
#define K_ALTO	280
#define K_ALTP	281
#define K_ALTQ	272
#define K_ALTR	275
#define K_ALTS	287
#define K_ALTT 276
#define K_ALTU	278
#define K_ALTV	303
#define K_ALTW	273
#define K_ALTX	301
#define K_ALTY	277
#define K_ALTZ	300

/* Additional ALT key combos */
#define K_ALT1	376
#define K_ALT2	377
#define K_ALT3	378
#define K_ALT4	379
#define K_ALT5	380
#define K_ALT6	381
#define K_ALT7	382
#define K_ALT8	383
#define K_ALT9	384
#define K_ALT0	385
#define K_ALTDASH 386
#define K_ALTEQU 387

/* Standard control keys */
#define K_CTRLA	1
#define K_CTRLB	2
#define K_CTRLC	3
#define K_CTRLD	4
#define K_CTRLE	5
#define K_CTRLF	6
#define K_CTRLG	7
#define K_CTRLH	8
#define K_CTRLI	9
#define K_CTRLJ	10
#define K_CTRLK	11
#define K_CTRLL	12
#define K_CTRLM	13
#define K_CTRLN	14
#define K_CTRLO	15
#define K_CTRLP	16
#define K_CTRLQ	17
#define K_CTRLR	18
#define K_CTRLS	19
#define K_CTRLT	20
#define K_CTRLU	21
#define K_CTRLV	22
#define K_CTRLW	23
#define K_CTRLX	24
#define K_CTRLY	25
#define K_CTRLZ	26

#define K_INS	338
#define K_DEL	339
