/********************************************************************/
/* A Small Real Time System for the Real-Time laboratory                 */
/* built by: A.Teitelbaum on an idea of H.G.Mendelbaum                  */
/* Jerusalem College of Technology, 5759-64 (1999)                            */
/* SchedAlgo64.CPP, short-term scheduler algorithms                */
/****************************************************************/


#include "smarts77.h"

int roundRobin( )
// Round Robin short-term algorithm 
{
	int count;
	int nextTask = (SMARTS.getCurrentTask()+1)%SMARTS.getTotalTasks( );
	for (count=0;
	     SMARTS.getStatus(nextTask)!=READY && count<SMARTS.getTotalTasks( );
	     count++)
	     nextTask=++nextTask%SMARTS.getTotalTasks( );
	if (count == SMARTS.getTotalTasks( ))	// no found READY task to run
		nextTask = SMARTS.getTotalTasks( );
	return nextTask;
}


int edf()
{
	int count;
	int nextTask = SMARTS.getTotalTasks();
	int minTime = MAXINT;

	for (count = 0; count < SMARTS.getTotalTasks(); count++) {
		if (SMARTS.getStatus(count) == READY && SMARTS.getRemainingTimeOfTask(count) < minTime) {
			minTime = SMARTS.getRemainingTimeOfTask(count);
			nextTask = count;	
		}
	}

	return nextTask;
}